# Generated by Django 3.2.16 on 2024-11-23 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_quantity_recipeingredient_value'),
        ('shoppinglist', '0004_auto_20241122_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveSmallIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.AddConstraint(
            model_name='useringredients',
            constraint=models.UniqueConstraint(fields=('user', 'ingredient'), name='unique_user_ingredient_cart'),
        ),
    ]
