# Generated by Django 3.2.16 on 2024-11-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0006_alter_useringredients_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorites',
            name='unique_user_recipe_fave',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_user_recipe_cart',
        ),
        migrations.RemoveConstraint(
            model_name='useringredients',
            name='unique_user_ingredient_cart',
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe_favorite'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe_shopping_cart'),
        ),
        migrations.AddConstraint(
            model_name='useringredients',
            constraint=models.UniqueConstraint(fields=('user', 'ingredient'), name='unique_user_ingredient_shopping_cart'),
        ),
    ]
