# Generated by Django 3.2.16 on 2024-11-26 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_rename_measure_unit_ingredient_measurement_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppinglist', '0007_auto_20241124_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='recipe',
            field=models.ForeignKey(help_text='Id рецепта, добавленного в список.', on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_favorites_list', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(help_text='Id пользователя, добавившего рецепт в список.', on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_favorites_owner', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(help_text='Id рецепта, добавленного в список.', on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_shoppingcart_list', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(help_text='Id пользователя, добавившего рецепт в список.', on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_shoppingcart_owner', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
