# Generated by Django 3.2.16 on 2024-11-15 16:36

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=None, help_text='Аватар или, как говорили встарь, юзерпик.', null=True, upload_to='users/avatars/', verbose_name='Аватар'),
        ),
    ]
