# Generated by Django 3.2.16 on 2024-11-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20241118_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.PositiveSmallIntegerField(help_text='Время приготовления в минутах.', verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.PositiveSmallIntegerField(help_text='Время приготовления в минутах.', verbose_name='Время приготовления'),
        ),
    ]
