version: '3'


volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/foodgram_backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    env_file: .env
    build: ./frontend/
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/

  gateway:
    build: ./gateway/
    depends_on:
      - backend
      - db
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80 