version: '3'


volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    restart: on-failure
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:    
    image: theartemio/foodgram_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    environement:
      - DJANGO_SUPERUSER_PASSWORD=$DJANGO_SUPERUSER_PASSWORD
    command: python manage.py createsuperuser

  frontend:
    image: theartemio/foodgram_frontend:latest
    env_file: .env  
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: theartemio/foodgram_gateway:latest
    env_file: .env
    depends_on:
      - backend
      - db
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/app/media
    ports:
      - 8000:80 