# Generated by Django 3.2.16 on 2024-12-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlists', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserIngredients',
        ),
    ]
