# Generated by Django 3.2.16 on 2024-11-15 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('measure_unit', models.CharField(help_text=('Единица измерения, которую можно использовать', ' для ингредиента. Рекомендуется писать целиком', ' или использовать понятное сокращение.'), max_length=150, verbose_name='Единица измерения')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(help_text=('Уникальный слаг, по которому можно указать тег', 'Рекомендуется использовать понятный', 'слаг, например транслитерацию или английское название.'), max_length=150, unique=True, verbose_name='Слаг')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название рецепта.', max_length=150, verbose_name='Название')),
                ('cover', models.ImageField(default=None, help_text='Картинка, иллюстрирующая рецепт.', null=True, upload_to='recipes/covers/', verbose_name='Иллюстрация')),
                ('description', models.TextField(blank=True, help_text='Подробное описание рецепта.', null=True, verbose_name='Описание')),
                ('time', models.PositiveSmallIntegerField(help_text='Время приготовления в минутах.', verbose_name='Время приготовления')),
                ('author', models.ForeignKey(help_text='Автор рецепта. Присваивается автоматически.', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ingredient', models.ManyToManyField(help_text=('Ингредиенты — продукты для приготовления блюда по рецепту.', ' Множественное поле с выбором из предустановленного списка', ' и с указанием количества и единицы измерения.'), to='recipes.Ingredient')),
                ('tag', models.ManyToManyField(help_text=('Теги, к которым относится рецепт.', ' Может быть несколько.'), null=True, related_name='tags', to='recipes.Tag', verbose_name='Теги')),
            ],
        ),
    ]
