# Generated by Django 3.2.16 on 2024-11-28 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(help_text='Автор рецепта. Присваивается автоматически.', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text=('Ингредиенты — продукты для приготовления блюда по рецепту.', ' Множественное поле с выбором из предустановленного списка', ' и с указанием количества и единицы измерения.'), through='recipes.RecipeIngredient', to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text=('Теги, к которым относится рецепт.', ' Может быть несколько.'), null=True, related_name='tags', to='recipes.Tag', verbose_name='Теги'),
        ),
    ]
