# Generated by Django 3.2.16 on 2024-11-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20241118_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cover',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooking_time', models.PositiveSmallIntegerField(help_text='Количество ингредиента, необходимое для рецепта.', verbose_name='Количество')),
                ('ingredient', models.ForeignKey(help_text='Id ингредиента.', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.ingredient', verbose_name='Ингредиент')),
                ('recipe', models.ForeignKey(help_text='Id рецепта, к которому относится ингредиент.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe', verbose_name='Рецепт')),
            ],
        ),
    ]
