# Generated by Django 3.2.16 on 2024-11-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20241118_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text=('Ингредиенты — продукты для приготовления блюда по рецепту.', ' Множественное поле с выбором из предустановленного списка', ' и с указанием количества и единицы измерения.'), through='recipes.RecipeIngredient', to='recipes.Ingredient'),
        ),
    ]
