# Generated by Django 3.2.16 on 2024-11-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='cooking_time',
            new_name='quantity',
        ),
    ]
