# Generated by Django 3.2.16 on 2024-11-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_cooking_time_recipeingredient_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity',
            new_name='value',
        ),
    ]
