# Generated by Django 3.2.16 on 2024-11-25 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_quantity_recipeingredient_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Присваивается автоматически.', verbose_name='Дата публикации рецепта'),
            preserve_default=False,
        ),
    ]
