# Generated by Django 3.2.16 on 2024-11-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20241125_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='value',
            new_name='amount',
        ),
    ]
