# Generated by Django 3.2.16 on 2024-11-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_rename_measure_unit_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(default=1, help_text='Подробное описание рецепта.', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
