# Generated by Django 3.2.16 on 2024-11-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_shortenedlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlinks',
            name='short_link_code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
